#!/bin/bash

# Get the current branch name
current_branch=$(git branch --show-current)

# Extract numbers from the branch name (e.g., charley/CLICKUP-1234 -> 1234)
branch_number=$(echo "$current_branch" | sed 's/[^0-9]*//g')

# Get the list of staged (cached) files
staged_files=$(git diff --cached --name-only)

# Iterate through staged files to check if branch number is included in any of them
for file in $staged_files; do
  if [[ $(cat "$file") != *"$branch_number"* ]]; then
    echo "ERROR: Commit message must include '$branch_number' , '$file', '$current_branch'"
    exit 1
  fi
done
